#############################################################################
# Makefile for building: vpiano
# Generated by qmake (2.01a) (Qt 4.7.0) on: ??? ?? 12 15:27:48 2011
# Project:  Piano.pro
# Template: app
# Command: d:\qt\2010.05\qt\bin\qmake.exe -spec d:\Qt\2010.05\qt\mkspecs\win32-g++ CONFIG+=release -o Makefile Piano.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DUNICODE -DQT_LARGEFILE_SUPPORT -D__WINDOWS_MM__ -DQT_DLL -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_THREAD_SUPPORT
CFLAGS        = -O2 -Wall $(DEFINES)
CXXFLAGS      = -Wall -O2 -frtti -fexceptions -mthreads -Wall $(DEFINES)
INCPATH       = -I"d:\Qt\2010.05\qt\include\QtCore" -I"d:\Qt\2010.05\qt\include\QtGui" -I"d:\Qt\2010.05\qt\include" -I"d:\Qt\2010.05\qt\include\QtTest" -I"d:\qt\2010.05\qt\include\vpiano" -I"d:\Qt\2010.05\qt\include\ActiveQt" -I"." -I"." -I"d:\Qt\2010.05\qt\mkspecs\win32-g++"
LINK        =        g++
LFLAGS        =        -enable-stdcall-fixup -Wl,-enable-auto-import -Wl,-enable-runtime-pseudo-reloc -Wl,-s -Wl,-subsystem,windows -mthreads -Wl
LIBS        =        -L"d:\Qt\2010.05\qt\lib" -Ld:/qt/2010.05/qt/lib -lvpianokeybd -lwinmm -lQtTest4 -lQtGui4 -lQtCore4 
QMAKE         = d:\qt\2010.05\qt\bin\qmake.exe
IDC           = d:\Qt\2010.05\qt\binidc.exe
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
DEL_FILE      = del
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
INSTALL_FILE    = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR     = $(COPY_DIR)

####### Output directory

OBJECTS_DIR   = . 

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		controller.cpp \
		RtMidi.cpp \
		octavekeybd.cpp \
		staff\partitura.cpp \
		staff\nota.cpp \
		staff\compas.cpp \
		renderpartitura.cpp \
		partituracommands.cpp \
		staff\currentstatus.cpp \
		staff\chordanalyst.cpp \
		staff\staff.cpp \
		staff\staffdao.cpp \
		staff\MidiMaker.cpp \
		staff\minHeap.cpp moc_mainwindow.cpp \
		moc_controller.cpp \
		moc_octavekeybd.cpp \
		moc_renderpartitura.cpp \
		qrc_katmus.cpp
OBJECTS       = main.o \
		mainwindow.o \
		controller.o \
		RtMidi.o \
		octavekeybd.o \
		partitura.o \
		nota.o \
		compas.o \
		renderpartitura.o \
		partituracommands.o \
		currentstatus.o \
		chordanalyst.o \
		staff.o \
		staffdao.o \
		MidiMaker.o \
		minHeap.o \
		moc_mainwindow.o \
		moc_controller.o \
		moc_octavekeybd.o \
		moc_renderpartitura.o \
		qrc_katmus.o
DIST          = 
QMAKE_TARGET  = vpiano
DESTDIR        =  #avoid trailing-slash linebreak
TARGET         = vpiano.exe
DESTDIR_TARGET = vpiano.exe

####### Implicit rules

.SUFFIXES: .cpp .cc .cxx .c

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

first: all
all: Makefile  $(DESTDIR_TARGET)

$(DESTDIR_TARGET): ui_mainwindow.h ui_controller.h $(OBJECTS) 
	$(LINK) $(LFLAGS) -o $(DESTDIR_TARGET) object_script.vpiano  $(LIBS)


Makefile: Piano.pro  d:/Qt/2010.05/qt/mkspecs/win32-g++/qmake.conf d:/Qt/2010.05/qt/mkspecs/qconfig.pri \
		d:/Qt/2010.05/qt/mkspecs/modules/qt_webkit_version.pri \
		d:/Qt/2010.05/qt/mkspecs/features/qt_functions.prf \
		d:/Qt/2010.05/qt/mkspecs/features/qt_config.prf \
		d:/Qt/2010.05/qt/mkspecs/features/exclusive_builds.prf \
		d:/Qt/2010.05/qt/mkspecs/features/default_pre.prf \
		d:/Qt/2010.05/qt/mkspecs/features/win32/default_pre.prf \
		d:/Qt/2010.05/qt/mkspecs/features/release.prf \
		d:/Qt/2010.05/qt/mkspecs/features/default_post.prf \
		d:/Qt/2010.05/qt/mkspecs/features/win32/default_post.prf \
		d:/Qt/2010.05/qt/mkspecs/features/qtestlib.prf \
		d:/Qt/2010.05/qt/mkspecs/features/win32/console.prf \
		d:/Qt/2010.05/qt/mkspecs/features/win32/rtti.prf \
		d:/Qt/2010.05/qt/mkspecs/features/win32/exceptions.prf \
		d:/Qt/2010.05/qt/mkspecs/features/win32/stl.prf \
		d:/Qt/2010.05/qt/mkspecs/features/shared.prf \
		d:/Qt/2010.05/qt/mkspecs/features/warn_on.prf \
		d:/Qt/2010.05/qt/mkspecs/features/qt.prf \
		d:/Qt/2010.05/qt/mkspecs/features/win32/thread.prf \
		d:/Qt/2010.05/qt/mkspecs/features/moc.prf \
		d:/Qt/2010.05/qt/mkspecs/features/resources.prf \
		d:/Qt/2010.05/qt/mkspecs/features/uic.prf \
		d:/Qt/2010.05/qt/mkspecs/features/yacc.prf \
		d:/Qt/2010.05/qt/mkspecs/features/lex.prf \
		d:/Qt/2010.05/qt/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec d:\Qt\2010.05\qt\mkspecs\win32-g++ CONFIG+=release -o Makefile Piano.pro
d:\Qt\2010.05\qt\mkspecs\qconfig.pri:
d:\Qt\2010.05\qt\mkspecs\modules\qt_webkit_version.pri:
d:\Qt\2010.05\qt\mkspecs\features\qt_functions.prf:
d:\Qt\2010.05\qt\mkspecs\features\qt_config.prf:
d:\Qt\2010.05\qt\mkspecs\features\exclusive_builds.prf:
d:\Qt\2010.05\qt\mkspecs\features\default_pre.prf:
d:\Qt\2010.05\qt\mkspecs\features\win32\default_pre.prf:
d:\Qt\2010.05\qt\mkspecs\features\release.prf:
d:\Qt\2010.05\qt\mkspecs\features\default_post.prf:
d:\Qt\2010.05\qt\mkspecs\features\win32\default_post.prf:
d:\Qt\2010.05\qt\mkspecs\features\qtestlib.prf:
d:\Qt\2010.05\qt\mkspecs\features\win32\console.prf:
d:\Qt\2010.05\qt\mkspecs\features\win32\rtti.prf:
d:\Qt\2010.05\qt\mkspecs\features\win32\exceptions.prf:
d:\Qt\2010.05\qt\mkspecs\features\win32\stl.prf:
d:\Qt\2010.05\qt\mkspecs\features\shared.prf:
d:\Qt\2010.05\qt\mkspecs\features\warn_on.prf:
d:\Qt\2010.05\qt\mkspecs\features\qt.prf:
d:\Qt\2010.05\qt\mkspecs\features\win32\thread.prf:
d:\Qt\2010.05\qt\mkspecs\features\moc.prf:
d:\Qt\2010.05\qt\mkspecs\features\resources.prf:
d:\Qt\2010.05\qt\mkspecs\features\uic.prf:
d:\Qt\2010.05\qt\mkspecs\features\yacc.prf:
d:\Qt\2010.05\qt\mkspecs\features\lex.prf:
d:\Qt\2010.05\qt\mkspecs\features\include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec d:\Qt\2010.05\qt\mkspecs\win32-g++ CONFIG+=release -o Makefile Piano.pro

dist:
	$(ZIP) vpiano.zip $(SOURCES) $(DIST) Piano.pro d:\Qt\2010.05\qt\mkspecs\qconfig.pri d:\Qt\2010.05\qt\mkspecs\modules\qt_webkit_version.pri d:\Qt\2010.05\qt\mkspecs\features\qt_functions.prf d:\Qt\2010.05\qt\mkspecs\features\qt_config.prf d:\Qt\2010.05\qt\mkspecs\features\exclusive_builds.prf d:\Qt\2010.05\qt\mkspecs\features\default_pre.prf d:\Qt\2010.05\qt\mkspecs\features\win32\default_pre.prf d:\Qt\2010.05\qt\mkspecs\features\release.prf d:\Qt\2010.05\qt\mkspecs\features\default_post.prf d:\Qt\2010.05\qt\mkspecs\features\win32\default_post.prf d:\Qt\2010.05\qt\mkspecs\features\qtestlib.prf d:\Qt\2010.05\qt\mkspecs\features\win32\console.prf d:\Qt\2010.05\qt\mkspecs\features\win32\rtti.prf d:\Qt\2010.05\qt\mkspecs\features\win32\exceptions.prf d:\Qt\2010.05\qt\mkspecs\features\win32\stl.prf d:\Qt\2010.05\qt\mkspecs\features\shared.prf d:\Qt\2010.05\qt\mkspecs\features\warn_on.prf d:\Qt\2010.05\qt\mkspecs\features\qt.prf d:\Qt\2010.05\qt\mkspecs\features\win32\thread.prf d:\Qt\2010.05\qt\mkspecs\features\moc.prf d:\Qt\2010.05\qt\mkspecs\features\resources.prf d:\Qt\2010.05\qt\mkspecs\features\uic.prf d:\Qt\2010.05\qt\mkspecs\features\yacc.prf d:\Qt\2010.05\qt\mkspecs\features\lex.prf d:\Qt\2010.05\qt\mkspecs\features\include_source_dir.prf  HEADERS RESOURCES IMAGES SOURCES OBJECTIVE_SOURCES FORMS YACCSOURCES YACCSOURCES LEXSOURCES 

clean: compiler_clean 
	-$(DEL_FILE) main.o mainwindow.o controller.o RtMidi.o octavekeybd.o partitura.o nota.o compas.o renderpartitura.o partituracommands.o currentstatus.o chordanalyst.o staff.o staffdao.o MidiMaker.o minHeap.o moc_mainwindow.o moc_controller.o moc_octavekeybd.o moc_renderpartitura.o qrc_katmus.o

distclean: clean
	-$(DEL_FILE) $(DESTDIR_TARGET)
	-$(DEL_FILE) Makefile

check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_controller.cpp moc_octavekeybd.cpp moc_renderpartitura.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_controller.cpp moc_octavekeybd.cpp moc_renderpartitura.cpp
moc_mainwindow.cpp: controller.h \
		staff/staff.h \
		staff/music_element.h \
		staff/currentstatus.h \
		renderpartitura.h \
		staff/partitura.h \
		staff/compas.h \
		staff/nota.h \
		rtmidi.h \
		RtError.h \
		rterror.h \
		octavekeybd.h \
		staff/chordanalyst.h \
		mainwindow.h
	D:\Qt\2010.05\qt\binmoc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 mainwindow.h -o moc_mainwindow.cpp

moc_controller.cpp: staff/staff.h \
		staff/music_element.h \
		staff/currentstatus.h \
		renderpartitura.h \
		staff/partitura.h \
		staff/compas.h \
		staff/nota.h \
		controller.h
	D:\Qt\2010.05\qt\binmoc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 controller.h -o moc_controller.cpp

moc_octavekeybd.cpp: octavekeybd.h
	D:\Qt\2010.05\qt\binmoc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 octavekeybd.h -o moc_octavekeybd.cpp

moc_renderpartitura.cpp: staff/partitura.h \
		staff/compas.h \
		staff/nota.h \
		staff/staff.h \
		staff/music_element.h \
		staff/currentstatus.h \
		renderpartitura.h
	D:\Qt\2010.05\qt\binmoc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 renderpartitura.h -o moc_renderpartitura.cpp

compiler_rcc_make_all: qrc_katmus.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_katmus.cpp
qrc_katmus.cpp: katmus.qrc \
		images/expand.png \
		images/icursorFusa_3.png \
		images/stop.png \
		images/run.png \
		images/cancel.png \
		images/cursorRedonda_1.png \
		images/magic2.png \
		images/cursorRedonda_2.png \
		images/cursorRedonda_3.png \
		images/cursorRedonda_4.png \
		images/icons64.png \
		images/magic1.png \
		images/iconoSemifusa.png \
		images/flat.png \
		images/cursorCorchea.png \
		images/important.png \
		images/cursorNegra_1.png \
		images/new.png \
		images/cursorNegra_4.png \
		images/cursorSemifusa.png \
		images/cursorNegra_2.png \
		images/cursorNegra_3.png \
		images/pause.png \
		images/zoomin.png \
		images/welcome.jpg \
		images/undo.png \
		images/iconarrow.png \
		images/copy.png \
		images/iconoBlanca.png \
		images/paste.png \
		images/cursorBlanca.png \
		images/wizard.png \
		images/iconoFusa.png \
		images/icursorSemicorchea.png \
		images/close.png \
		images/piano.png \
		images/no.png \
		images/iconoNegra.png \
		images/icons8.png \
		images/blackc.png \
		images/cursorSemifusa_4.png \
		images/ok.png \
		images/icons2.png \
		images/corchete8.png \
		images/corchete16.png \
		images/cursorSemifusa_2.png \
		images/icons4.png \
		images/cursorSemifusa_3.png \
		images/icursorCorchea_4.png \
		images/cursorSemifusa_1.png \
		images/icursorCorchea_2.png \
		images/locale.png \
		images/s1.png \
		images/wave.png \
		images/s2.png \
		images/s4.png \
		images/icons1.png \
		images/icursorCorchea_3.png \
		images/newpro.png \
		images/iconoCorchea.png \
		images/icursorCorchea_1.png \
		images/s8.png \
		images/icons16.png \
		images/iconoRedonda.png \
		images/corchete32.png \
		images/exit.png \
		images/cursorFusa.png \
		images/blancc.png \
		images/sharp.png \
		images/corchete64.png \
		images/iconcompas.png \
		images/icursorSemicorchea_1.png \
		images/icursorSemifusa_2.png \
		images/icursorSemicorchea_2.png \
		images/icursorSemicorchea_3.png \
		images/icursorSemifusa_4.png \
		images/icons32.png \
		images/icursorSemicorchea_4.png \
		images/icursorSemifusa_3.png \
		images/iconpent.png \
		images/icursorSemifusa_1.png \
		images/mn_0.png \
		images/mn_1.png \
		images/mn_2.png \
		images/unknow.png \
		images/mn_3.png \
		images/mn_4.png \
		images/mn_5.png \
		images/mn_6.png \
		images/s16.png \
		images/mn_7.png \
		images/restzoom.png \
		images/mn_8.png \
		images/redo.png \
		images/mn_9.png \
		images/cursorFusa_4.png \
		images/delete.png \
		images/punt.png \
		images/cursorFusa_2.png \
		images/cursorFusa_3.png \
		images/cursorCorchea_4.png \
		images/cursorFusa_1.png \
		images/cursorCorchea_2.png \
		images/cursorCorchea_3.png \
		images/cursorCorchea_1.png \
		images/configure.png \
		images/icursorCorchea.png \
		images/s32.png \
		images/cursorNegra.png \
		images/cursor.png \
		images/cursorSemicorchea.png \
		images/cursorBlanca_4.png \
		images/cursorBlanca_2.png \
		images/cursorBlanca_3.png \
		images/cursorBlanca_1.png \
		images/icursorFusa.png \
		images/claveSol.png \
		images/save.png \
		images/claveFa.png \
		images/icursorSemifusa.png \
		images/play.png \
		images/magic.png \
		images/s64.png \
		images/saveas.png \
		images/collapse.png \
		images/open.png \
		images/zoomout.png \
		images/iconoSemicorchea.png \
		images/cut.png \
		images/4_4.png \
		images/3_4.png \
		images/6_8.png \
		images/metrica.png \
		images/2_4.png \
		images/cursorRedonda.png \
		images/cursorSemicorchea_1.png \
		images/cursorSemicorchea_2.png \
		images/cursorSemicorchea_3.png \
		images/iconproject.png \
		images/icursorFusa_1.png \
		images/cursorSemicorchea_4.png \
		images/icursorFusa_4.png \
		images/icursorFusa_2.png
	d:\Qt\2010.05\qt\bin\rcc.exe -name katmus katmus.qrc -o qrc_katmus.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_controller.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_controller.h
ui_mainwindow.h: mainwindow.ui
	d:\Qt\2010.05\qt\binuic.exe mainwindow.ui -o ui_mainwindow.h

ui_controller.h: controller.ui
	d:\Qt\2010.05\qt\binuic.exe controller.ui -o ui_controller.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 



####### Compile

main.o: main.cpp mainwindow.h \
		controller.h \
		staff/staff.h \
		staff/music_element.h \
		staff/currentstatus.h \
		renderpartitura.h \
		staff/partitura.h \
		staff/compas.h \
		staff/nota.h \
		rtmidi.h \
		RtError.h \
		rterror.h \
		octavekeybd.h \
		staff/chordanalyst.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		controller.h \
		staff/staff.h \
		staff/music_element.h \
		staff/currentstatus.h \
		renderpartitura.h \
		staff/partitura.h \
		staff/compas.h \
		staff/nota.h \
		rtmidi.h \
		RtError.h \
		rterror.h \
		octavekeybd.h \
		staff/chordanalyst.h \
		ui_mainwindow.h \
		midiref.h \
		staff/staffdao.h \
		staff/MidiMaker.h \
		staff/minHeap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

controller.o: controller.cpp controller.h \
		staff/staff.h \
		staff/music_element.h \
		staff/currentstatus.h \
		renderpartitura.h \
		staff/partitura.h \
		staff/compas.h \
		staff/nota.h \
		ui_controller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o controller.o controller.cpp

RtMidi.o: RtMidi.cpp RtMidi.h \
		RtError.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RtMidi.o RtMidi.cpp

octavekeybd.o: octavekeybd.cpp octavekeybd.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o octavekeybd.o octavekeybd.cpp

partitura.o: staff/partitura.cpp staff/partitura.h \
		staff/compas.h \
		staff/nota.h \
		staff/staff.h \
		staff/music_element.h \
		staff/currentstatus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o partitura.o staff\partitura.cpp

nota.o: staff/nota.cpp staff/nota.h \
		staff/compas.h \
		staff/staff.h \
		staff/music_element.h \
		staff/currentstatus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nota.o staff\nota.cpp

compas.o: staff/compas.cpp staff/compas.h \
		staff/nota.h \
		staff/staff.h \
		staff/music_element.h \
		staff/currentstatus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o compas.o staff\compas.cpp

renderpartitura.o: renderpartitura.cpp staff/nota.h \
		staff/partitura.h \
		staff/compas.h \
		staff/staff.h \
		staff/music_element.h \
		staff/currentstatus.h \
		renderpartitura.h \
		partituracommands.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o renderpartitura.o renderpartitura.cpp

partituracommands.o: partituracommands.cpp partituracommands.h \
		staff/nota.h \
		staff/compas.h \
		staff/staff.h \
		staff/music_element.h \
		staff/currentstatus.h \
		staff/partitura.h \
		renderpartitura.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o partituracommands.o partituracommands.cpp

currentstatus.o: staff/currentstatus.cpp staff/currentstatus.h \
		staff/music_element.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o currentstatus.o staff\currentstatus.cpp

chordanalyst.o: staff/chordanalyst.cpp staff/chordanalyst.h \
		staff/music_element.h \
		staff/staff.h \
		staff/currentstatus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chordanalyst.o staff\chordanalyst.cpp

staff.o: staff/staff.cpp staff/staff.h \
		staff/music_element.h \
		staff/currentstatus.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o staff.o staff\staff.cpp

staffdao.o: staff/staffdao.cpp staff/staffdao.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o staffdao.o staff\staffdao.cpp

MidiMaker.o: staff/MidiMaker.cpp staff/MidiMaker.h \
		staff/music_element.h \
		staff/staff.h \
		staff/currentstatus.h \
		staff/minHeap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MidiMaker.o staff\MidiMaker.cpp

minHeap.o: staff/minHeap.cpp staff/minHeap.h \
		staff/music_element.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minHeap.o staff\minHeap.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_controller.o: moc_controller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_controller.o moc_controller.cpp

moc_octavekeybd.o: moc_octavekeybd.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_octavekeybd.o moc_octavekeybd.cpp

moc_renderpartitura.o: moc_renderpartitura.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_renderpartitura.o moc_renderpartitura.cpp

qrc_katmus.o: qrc_katmus.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_katmus.o qrc_katmus.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

